# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/NAS/Dropbox/Documents/steamlink-sdk/examples/supermariowar

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/NAS/Dropbox/Documents/steamlink-sdk/examples/supermariowar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /media/NAS/Dropbox/Documents/steamlink-sdk/examples/supermariowar/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/NAS/Dropbox/Documents/steamlink-sdk/examples/supermariowar/CMakeFiles /media/NAS/Dropbox/Documents/steamlink-sdk/examples/supermariowar/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/NAS/Dropbox/Documents/steamlink-sdk/examples/supermariowar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named enet

# Build rule for target.
enet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 enet
.PHONY : enet

# fast build rule for target.
enet/fast:
	$(MAKE) -f dependencies/enet/CMakeFiles/enet.dir/build.make dependencies/enet/CMakeFiles/enet.dir/build
.PHONY : enet/fast

#=============================================================================
# Target rules for targets named format

# Build rule for target.
format: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 format
.PHONY : format

# fast build rule for target.
format/fast:
	$(MAKE) -f dependencies/yaml-cpp-noboost/CMakeFiles/format.dir/build.make dependencies/yaml-cpp-noboost/CMakeFiles/format.dir/build
.PHONY : format/fast

#=============================================================================
# Target rules for targets named releasable

# Build rule for target.
releasable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 releasable
.PHONY : releasable

# fast build rule for target.
releasable/fast:
	$(MAKE) -f dependencies/yaml-cpp-noboost/CMakeFiles/releasable.dir/build.make dependencies/yaml-cpp-noboost/CMakeFiles/releasable.dir/build
.PHONY : releasable/fast

#=============================================================================
# Target rules for targets named yaml-cpp

# Build rule for target.
yaml-cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yaml-cpp
.PHONY : yaml-cpp

# fast build rule for target.
yaml-cpp/fast:
	$(MAKE) -f dependencies/yaml-cpp-noboost/CMakeFiles/yaml-cpp.dir/build.make dependencies/yaml-cpp-noboost/CMakeFiles/yaml-cpp.dir/build
.PHONY : yaml-cpp/fast

#=============================================================================
# Target rules for targets named debuggable

# Build rule for target.
debuggable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debuggable
.PHONY : debuggable

# fast build rule for target.
debuggable/fast:
	$(MAKE) -f dependencies/yaml-cpp-noboost/CMakeFiles/debuggable.dir/build.make dependencies/yaml-cpp-noboost/CMakeFiles/debuggable.dir/build
.PHONY : debuggable/fast

#=============================================================================
# Target rules for targets named CommonFiles

# Build rule for target.
CommonFiles: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CommonFiles
.PHONY : CommonFiles

# fast build rule for target.
CommonFiles/fast:
	$(MAKE) -f src/common/CMakeFiles/CommonFiles.dir/build.make src/common/CMakeFiles/CommonFiles.dir/build
.PHONY : CommonFiles/fast

#=============================================================================
# Target rules for targets named NetplayFiles

# Build rule for target.
NetplayFiles: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NetplayFiles
.PHONY : NetplayFiles

# fast build rule for target.
NetplayFiles/fast:
	$(MAKE) -f src/common_netplay/CMakeFiles/NetplayFiles.dir/build.make src/common_netplay/CMakeFiles/NetplayFiles.dir/build
.PHONY : NetplayFiles/fast

#=============================================================================
# Target rules for targets named smw

# Build rule for target.
smw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smw
.PHONY : smw

# fast build rule for target.
smw/fast:
	$(MAKE) -f src/smw/CMakeFiles/smw.dir/build.make src/smw/CMakeFiles/smw.dir/build
.PHONY : smw/fast

#=============================================================================
# Target rules for targets named smw-leveledit

# Build rule for target.
smw-leveledit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smw-leveledit
.PHONY : smw-leveledit

# fast build rule for target.
smw-leveledit/fast:
	$(MAKE) -f src/leveleditor/CMakeFiles/smw-leveledit.dir/build.make src/leveleditor/CMakeFiles/smw-leveledit.dir/build
.PHONY : smw-leveledit/fast

#=============================================================================
# Target rules for targets named smw-worldedit

# Build rule for target.
smw-worldedit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smw-worldedit
.PHONY : smw-worldedit

# fast build rule for target.
smw-worldedit/fast:
	$(MAKE) -f src/worldeditor/CMakeFiles/smw-worldedit.dir/build.make src/worldeditor/CMakeFiles/smw-worldedit.dir/build
.PHONY : smw-worldedit/fast

#=============================================================================
# Target rules for targets named smw-server

# Build rule for target.
smw-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smw-server
.PHONY : smw-server

# fast build rule for target.
smw-server/fast:
	$(MAKE) -f src/server/CMakeFiles/smw-server.dir/build.make src/server/CMakeFiles/smw-server.dir/build
.PHONY : smw-server/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... package_source"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... package"
	@echo "... enet"
	@echo "... format"
	@echo "... releasable"
	@echo "... yaml-cpp"
	@echo "... debuggable"
	@echo "... CommonFiles"
	@echo "... NetplayFiles"
	@echo "... smw"
	@echo "... smw-leveledit"
	@echo "... smw-worldedit"
	@echo "... smw-server"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

