#ifndef MATCHTYPES_H
#define MATCHTYPES_H

enum MatchType {
	MATCH_TYPE_SINGLE_GAME = 0,
	MATCH_TYPE_TOURNAMENT = 1,
	MATCH_TYPE_TOUR = 2,
	MATCH_TYPE_WORLD = 4,
	MATCH_TYPE_MINIGAME = 3,
	MATCH_TYPE_QUICK_GAME = 5,
	MATCH_TYPE_NET_GAME = 6
};

#endif // MATCHTYPES_H
