#pragma once

enum GameModeType {
    game_mode_classic,
    game_mode_frag,
    game_mode_timelimit,
    game_mode_jail,
    game_mode_coins,
    game_mode_stomp,
    game_mode_eggs,
    game_mode_ctf,
    game_mode_chicken,
    game_mode_tag,
    game_mode_star,
    game_mode_domination,
    game_mode_koth,
    game_mode_race,
    game_mode_owned,
    game_mode_frenzy,
    game_mode_survival,
    game_mode_greed,
    game_mode_health,
    game_mode_collection,
    game_mode_chase,
    game_mode_shyguytag,
    GAMEMODE_LAST,
    game_mode_bonus = 999,
    game_mode_pipe_minigame = 1000,
    game_mode_boss_minigame = 1001,
    game_mode_boxes_minigame = 1002
};
