name: Build - Web
on:
  workflow_call:

jobs:
  emscripten:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Emscripten
        working-directory: /tmp
        run: |
          git clone https://github.com/emscripten-core/emsdk.git --depth=1
          cd emsdk
          ./emsdk install 5.0.2
          ./emsdk activate 5.0.2

      - name: Build
        run: |
          source /tmp/emsdk/emsdk_env.sh
          emcc -v
          emcmake cmake \
            -B build \
            -G Ninja \
            -DNO_NETWORK=1 \
            -DDISABLE_SYSLIB_CHECKS=1 \
            -DUSE_SDL2_LIBS=1 \
            -DUSE_BUNDLED_ENET=ON \
            -DUSE_BUNDLED_YAMLCPP=ON
          cmake --build build --target smw
