name: Build
on: [push, pull_request, workflow_dispatch]


concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true


jobs:
  build-linux:
    if: &should-run >
      github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    name: Linux
    uses: ./.github/workflows/build_linux.yml

  build-macos:
    if: *should-run
    name: macOS
    uses: ./.github/workflows/build_macos.yml

  build-windows:
    if: *should-run
    name: Windows
    uses: ./.github/workflows/build_windows.yml

  build-emcc:
    if: *should-run
    name: Web
    uses: ./.github/workflows/build_emcc.yml

  build-android:
    if: *should-run
    name: Android
    uses: ./.github/workflows/build_android.yml
